<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="description" content="SGML and XML" /> 
  <meta name="keywords" content="HTML, CSS, JAVASCRIPT" />
  <meta name="author" content="aaryan" />
  <title>welcome to SGML and XML</title>
  <link href= "styles/sgml.css" rel="stylesheet"/>
</head>

<body>

	<header>
	<img src= "images/sgml-xml-html.png" id="logo" alt="logo"/>
	<h1> INTRODUTION to SGML and XML </h1>
  <nav>
    <a href="index.html" class="menu" target="_blank" title="open index page">INTRO</a>
    <a href="topic.html" class="menu" target="_blank" title="topic">TOPIC</a>
    
    <a href="quiz.html" class="menu" target="_blank" title="QUIZ">QUIZ</a>
    <a href="enhancement.html" class="menu" target="_blank" title="enhancement">ENHANCEMENTS</a>
    <a href="enhancement2.html" class="menu" target="_blank" title="enhancement">ENHANCEMENTS2</a>
  </nav>
  </header>
  <br>
  <hr>